import { useEffect, useRef, useState } from 'react';
import { Terminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import { SearchAddon } from '@xterm/addon-search';
import { TerminalIcon } from './Icons';
type Status='checking'|'missing-mai'|'missing-npm'|'paused'|'running'|'exited'|'error';
export function TerminalPanel({ title, onRename, onDuplicate, restored=false, restoreMode='automatic' }:{title:string;onRename:(v:string)=>void;onDuplicate:()=>void;restored?:boolean;restoreMode?:'automatic'|'confirm'|'manual'}) {
 const host=useRef<HTMLDivElement>(null), terminalId=useRef<string | undefined>(undefined), terminal=useRef<Terminal | undefined>(undefined), search=useRef<SearchAddon | undefined>(undefined);
 const [status,setStatus]=useState<Status>('checking'),[installing,setInstalling]=useState(false),[showSearch,setShowSearch]=useState(false),[query,setQuery]=useState(''),[fontSize,setFontSize]=useState(14),[error,setError]=useState('');
 useEffect(()=>{let alive=true;void window.maiDesktop!.cliStatus().then(s=>{if(alive)setStatus(!s.npm?'missing-npm':s.mai?(restored&&restoreMode!=='automatic'?'paused':'running'):'missing-mai')}).catch(e=>{setError(String(e));setStatus('error')});return()=>{alive=false}},[]);
 useEffect(()=>{if(status!=='running'||!host.current)return; const term=new Terminal({cursorBlink:true,fontSize,fontFamily:'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',scrollback:10000,theme:{background:'#090b12',foreground:'#e9edf7',cursor:'#19d3c5',selectionBackground:'#315b7355',black:'#131722',brightBlack:'#667085'}}); const fit=new FitAddon(),find=new SearchAddon();term.loadAddon(fit);term.loadAddon(find);term.open(host.current);terminal.current=term;search.current=find;fit.fit();term.focus();
  const id=crypto.randomUUID();terminalId.current=id;let disposed=false;
  const offData=window.maiDesktop!.onTerminalData(p=>{if(p.id===id)term.write(p.data)}),offExit=window.maiDesktop!.onTerminalExit(p=>{if(p.id===id)setStatus('exited')});
  const input=term.onData(data=>window.maiDesktop!.writeTerminal(id,data));
  void window.maiDesktop!.startTerminal(id,installing?'install':'mai').catch(e=>{setError(String(e));setStatus('error')});
  const resize=new ResizeObserver(()=>{try{fit.fit();window.maiDesktop!.resizeTerminal(id,term.cols,term.rows)}catch{}});resize.observe(host.current);
  const visible=()=>setTimeout(()=>{try{fit.fit();term.focus()}catch{}},50);document.addEventListener('visibilitychange',visible);window.addEventListener('resize',visible);
  return()=>{disposed=true;void disposed;resize.disconnect();document.removeEventListener('visibilitychange',visible);window.removeEventListener('resize',visible);input.dispose();offData();offExit();window.maiDesktop!.killTerminal(id);terminalId.current=undefined;terminal.current=undefined;term.dispose()};
 },[status,installing]);
 useEffect(()=>{terminal.current?.options&&(terminal.current.options.fontSize=fontSize)},[fontSize]);
 const restart=()=>{setInstalling(false);setStatus('checking');void window.maiDesktop!.cliStatus().then(s=>setStatus(s.mai?'running':s.npm?'missing-mai':'missing-npm'))};
 if(status==='checking')return <div className="center-state"><div className="loader"/><h2>Recherche de mAI CLI…</h2></div>;
 if(status==='missing-npm')return <div className="center-state"><TerminalIcon/><h2>Node.js et npm sont requis</h2><p>Installez Node.js, puis relancez mAI.</p><code>https://nodejs.org</code></div>;
 if(status==='paused')return <div className="center-state"><TerminalIcon/><h2>Terminal restauré</h2><p>{restoreMode==='confirm'?'Confirmez la relance de mAI dans une nouvelle session locale.':'La relance automatique est désactivée dans les paramètres.'}</p><button className="primary" onClick={()=>setStatus('running')}>Démarrer mAI</button></div>;
 if(status==='missing-mai')return <div className="center-state"><TerminalIcon/><h2>mAI CLI n’est pas encore installé</h2><p>Cette action installe le paquet global après votre confirmation.</p><code>npm install -g @mdevs/mai-cli</code><button className="primary" onClick={()=>{setInstalling(true);setStatus('running')}}>Installer mAI CLI</button></div>;
 if(status==='exited')return <div className="center-state"><TerminalIcon/><h2>La session est terminée</h2><div className="state-actions"><button className="primary" onClick={restart}>Relancer mAI</button><button onClick={onDuplicate}>Nouveau terminal</button></div></div>;
 if(status==='error')return <div className="center-state"><TerminalIcon/><h2>Impossible de démarrer le terminal</h2><p>{error}</p><button className="primary" onClick={restart}>Réessayer</button></div>;
 return <div className="terminal-wrap"><div className="terminal-tools"><button onClick={()=>{const n=prompt('Nom du terminal',title);if(n?.trim())onRename(n.trim())}}>Renommer</button><button onClick={onDuplicate}>Dupliquer</button><button onClick={()=>setShowSearch(v=>!v)}>Rechercher</button><button onClick={()=>terminal.current?.clear()}>Effacer</button><button onClick={()=>void navigator.clipboard.writeText(terminal.current?.getSelection()||'')}>Copier</button><button onClick={()=>void navigator.clipboard.readText().then(t=>terminalId.current&&window.maiDesktop!.writeTerminal(terminalId.current,t))}>Coller</button><span/><button onClick={()=>setFontSize(v=>Math.max(10,v-1))}>A−</button><button onClick={()=>setFontSize(v=>Math.min(24,v+1))}>A+</button></div>{showSearch&&<div className="terminal-search"><input autoFocus value={query} onChange={e=>{setQuery(e.target.value);search.current?.findNext(e.target.value)}} onKeyDown={e=>{if(e.key==='Enter')search.current?.findNext(query);if(e.key==='Escape')setShowSearch(false)}} placeholder="Rechercher dans la sortie…"/><button onClick={()=>search.current?.findPrevious(query)}>↑</button><button onClick={()=>search.current?.findNext(query)}>↓</button></div>}<div className="terminal-shell"><div ref={host} className="terminal-host"/></div></div>;
}
